### PR TITLE
Ports server to krestrel

### PR DESCRIPTION
**Pull request by Karolis2011**
Uses integrated ASP net HTTP server and cleans up server code by using controller.

### CODE REVIEW

**Comment by Karolis2011** [comment]
So to sumarize - NTSL service manages state of interpreter - and it's relative programs, while Controler handles IO, and exceptions. And maybe else. Currently some code from service should be moved to controller.

**Comment by TehFlaminTaco** [comment]
I can't deny this looks a lot cleaner. Also looks like it'll need a bit of re-implementation on the BYOND side, but that shouldn't be too hard.

**Comment by TehFlaminTaco** [comment]
When  I run this I get thrown `InvalidOperationException: Unable to resolve service for type 'ByondLang.Services.NTSLService' while attempting to activate 'ByondLang.Controllers.NTSLController'.` Am I doing something wrong?

**Comment by Karolis2011** [comment]
Oh I forgot to register service, I will do that in a moment.

**Pull request merged**
